
[files]
extend-exclude = [".git/"]
# Check hidden files.
ignore-hidden = false

[default]
# File names produce false positives.
check-filename = false

[default.extend-words]
tre = "tre"     # Tool name.
serie = "serie" # Tool name.
