format = """
[╭─](surface0)$os$username$hostname$directory$git_branch$git_status$fill$cmd_duration$status$time
[╰─](surface0)$character"""
add_newline = true
scan_timeout = 20
command_timeout = 800
palette = "tokyo_night"

[palettes.tokyo_night]
background = "#1a1b26"
surface0 = "#3b4261"
surface1 = "#565f89"
foreground = "#c0caf5"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
red = "#f7768e"
yellow = "#e0af68"

[os]
format = "[$symbol]($style)"
disabled = false
style = "bold blue"

[os.symbols]
Linux = "󰌽 "

[username]
show_always = false
style_user = "bold blue"

[hostname]
ssh_only = true
format = "[](fg:cyan)[󰒋 $hostname]($style)[](fg:cyan) "
style = "bg:cyan fg:background bold"

[directory]
read_only_style = "bg:blue fg:background"
format = "[](fg:blue)[$path$read_only]($style)[](fg:blue) "
style = "bg:blue fg:background bold"
truncation_length = 4
truncate_to_repo = true
read_only = " 󰌾"
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
vimcmd_symbol = "[❮](bold magenta) "

[git_branch]
format = "[](fg:magenta)[$symbol$branch(:$remote_branch)]($style)[](fg:magenta) "
symbol = " "
style = "bg:magenta fg:background bold"

[git_status]
format = "([$all_status$ahead_behind ]($style))"
style = "bold yellow"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"

[fill]
symbol = "─"
style = "surface0"

[cmd_duration]
min_time = 500
format = " [󱎫 $duration](yellow)"

[status]
disabled = false
format = " [$symbol$status]($style)"
symbol = "✘ "
style = "bold red"

[time]
disabled = false
format = " [ $time]($style)"
time_format = "%H:%M"
style = "surface1"
