format = """
$directory$git_branch$git_status$character"""
add_newline = false

[directory]
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[>](bold green)"
error_symbol   = "[>](bold red)"

[git_branch]
symbol = " "

[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
